#!/usr/bin/env bash
# Dependency update skill script
# Checks for outdated dependencies and creates a PR with updates

set -euo pipefail

# ─── Configuration ────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../../.." && pwd)"
BRANCH_PREFIX="chore/dependency-update"
DATE_STAMP="$(date +%Y%m%d)"
UPDATE_BRANCH="${BRANCH_PREFIX}-${DATE_STAMP}"

# ─── Helpers ──────────────────────────────────────────────────────────────────
log()  { echo "[dep-update] $*"; }
warn() { echo "[dep-update] WARN: $*" >&2; }
die()  { echo "[dep-update] ERROR: $*" >&2; exit 1; }

require_cmd() {
  command -v "$1" &>/dev/null || die "Required command not found: $1"
}

# ─── Pre-flight checks ────────────────────────────────────────────────────────
require_cmd git
require_cmd python3
require_cmd pip

cd "${REPO_ROOT}"

# Ensure we are on a clean working tree before branching
if [[ -n "$(git status --porcelain)" ]]; then
  die "Working tree is dirty. Commit or stash changes before running dependency updates."
fi

# ─── Detect package manager ───────────────────────────────────────────────────
if [[ -f "pyproject.toml" ]]; then
  PKG_MANAGER="pyproject"
elif [[ -f "requirements.txt" ]]; then
  PKG_MANAGER="pip"
else
  die "No supported package manifest found (pyproject.toml or requirements.txt)."
fi

log "Detected package manager: ${PKG_MANAGER}"

# ─── Create update branch ─────────────────────────────────────────────────────
DEFAULT_BRANCH="$(git remote show origin 2>/dev/null | awk '/HEAD branch/ {print $NF}' || echo 'main')"
git fetch origin "${DEFAULT_BRANCH}" --quiet
git checkout -b "${UPDATE_BRANCH}" "origin/${DEFAULT_BRANCH}"
log "Created branch: ${UPDATE_BRANCH}"

# ─── Collect outdated packages ────────────────────────────────────────────────
OUTDATED_JSON="$(pip list --outdated --format=json 2>/dev/null || echo '[]')"
OUTDATED_COUNT="$(echo "${OUTDATED_JSON}" | python3 -c "import sys,json; print(len(json.load(sys.stdin)))")"

if [[ "${OUTDATED_COUNT}" -eq 0 ]]; then
  log "All dependencies are up to date. Nothing to do."
  git checkout "${DEFAULT_BRANCH}"
  git branch -D "${UPDATE_BRANCH}"
  exit 0
fi

log "Found ${OUTDATED_COUNT} outdated package(s)."

# ─── Apply updates ────────────────────────────────────────────────────────────
if [[ "${PKG_MANAGER}" == "pyproject" ]]; then
  require_cmd uv
  log "Upgrading dependencies via uv ..."
  uv lock --upgrade
  uv sync
else
  log "Upgrading dependencies via pip ..."
  pip install --upgrade $(pip list --outdated --format=columns | tail -n +3 | awk '{print $1}') \
    && pip freeze > requirements.txt
fi

# ─── Run tests to validate updates ───────────────────────────────────────────
log "Running test suite to validate updated dependencies ..."
if command -v pytest &>/dev/null; then
  pytest --tb=short -q || die "Tests failed after dependency update. Aborting."
else
  warn "pytest not found — skipping test validation."
fi

# ─── Commit changes ───────────────────────────────────────────────────────────
git add --all

COMMIT_BODY="$(echo "${OUTDATED_JSON}" | python3 - <<'PY'
import sys, json
pkgs = json.load(sys.stdin)
lines = [f"- {p['name']}: {p['version']} -> {p['latest_version']}" for p in pkgs]
print("\n".join(lines))
PY
)"

git commit -m "chore: update dependencies (${DATE_STAMP})" \
           -m "${COMMIT_BODY}"

log "Changes committed."

# ─── Push branch ──────────────────────────────────────────────────────────────
git push origin "${UPDATE_BRANCH}"
log "Branch pushed: ${UPDATE_BRANCH}"

# ─── Open PR (GitHub CLI) ─────────────────────────────────────────────────────
if command -v gh &>/dev/null; then
  PR_BODY="## Automated Dependency Update\n\nThe following packages were upgraded:\n\n${COMMIT_BODY}\n\n> Generated by the dependency-update skill on ${DATE_STAMP}."
  gh pr create \
    --base "${DEFAULT_BRANCH}" \
    --head "${UPDATE_BRANCH}" \
    --title "chore: dependency updates ${DATE_STAMP}" \
    --body "$(printf '%b' "${PR_BODY}")" \
    --label "dependencies" || warn "PR creation failed — push succeeded, create PR manually."
else
  warn "GitHub CLI (gh) not found. Push succeeded; please open a PR manually for branch '${UPDATE_BRANCH}'."
fi

log "Dependency update complete."
